
# Project name.
name: 'dbt_faker'
version: '1.0.0'
require-dbt-version: ">=1.3.0"
config-version: 2

# The "profile" dbt uses for this project.
profile: 'dbt_faker'

# Configuration paths.
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  faker_enabled: true
