name: Unit tests
on:
  push:
    branches:
      - main
  pull_request:
  
env:
 DBT_PROFILES_DIR: "${{ github.workspace }}/integration_tests"
 DBT_SNOWFLAKE_USERNAME: ${{ secrets.DBT_SNOWFLAKE_USERNAME }}
 DBT_SNOWFLAKE_PW: ${{ secrets.DBT_SNOWFLAKE_PW }}
 DBT_SNOWFLAKE_ROLE: ${{ secrets.DBT_SNOWFLAKE_ROLE }}
 DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
 DBT_SNOWFLAKE_DATABASE: ${{ secrets.DBT_SNOWFLAKE_DATABASE }}
 DBT_SNOWFLAKE_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_WAREHOUSE }}
 DBT_SNOWFLAKE_SCHEMA: ${{ secrets.DBT_SNOWFLAKE_SCHEMA }}

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
      - name: Install dbt and deps
        working-directory: "${{ github.workspace }}/integration_tests"
        run: |
          pip install dbt-snowflake
          dbt deps
      - name: Run unit tests
        working-directory: "${{ github.workspace }}/integration_tests"
        run: |
          dbt run-operation test_macros
      - name: Generate and Run Python Model
        working-directory: "${{ github.workspace }}/integration_tests"
        run: |
          dbt --quiet run-operation generate_faker_model > models/python.py
          dbt run
      - name: Run dbt Tests
        working-directory: "${{ github.workspace }}/integration_tests"
        run: |
          dbt test
      - id: exit
        run: exit ${{ steps.apply.outputs.exitcode }}
