name: Unit tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
      - name: Install dbt
        working-directory: "${{ github.workspace }}/integration_tests"
        run: |
          pip install dbt-snowflake
      - name: Run unit tests
        working-directory: "${{ github.workspace }}/integration_tests"
        run: |
          dbt run-operation test_macros
      - id: exit
        run: exit ${{ steps.apply.outputs.exitcode }}
